tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homeport/tap"
tap "jdx/tap"
tap "koekeishiya/formulae"
tap "prezi/security", "git@github.com:prezi/homebrew-security"
brew "automake"
brew "xz"
brew "awscli"
brew "certifi"
brew "docker-credential-helper-ecr"
brew "gnupg"
brew "jq"
brew "libssh2"
brew "libgit2"
brew "node"
brew "pkgconf"
brew "pyyaml"
brew "rust"
brew "sk"
brew "teleport"
brew "zlib"
brew "prezi/security/aws-login"
brew "prezi/security/ptp"
cask "audacity"
cask "font-fira-code-nerd-font"
cask "font-new-york"
cask "font-sf-pro"
mas "Bitwarden", id: 1352778147
mas "DaVinci Resolve", id: 571213070
mas "iMovie", id: 408981434
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "WhatsApp", id: 310633997
vscode "animus-coop.vscode-elixir-mix-formatter"
vscode "benvp.vscode-hex-pm-intellisense"
vscode "bradlc.vscode-tailwindcss"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "gitlab.gitlab-workflow"
vscode "gp-pereira.refatorex"
vscode "jakebecker.elixir-ls"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "pantajoe.vscode-elixir-credo"
vscode "phoenixframework.phoenix"
