tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "asdf"
brew "git"
brew "glab"
brew "gnupg"
brew "gnupg-pkcs11-scd"
brew "htop"
brew "mas"
brew "mmv"
brew "ncdu"
brew "neovim"
brew "pcsc-lite"
brew "pinentry-mac"
brew "pwgen"
brew "rcm"
brew "starship"
brew "tmux"
cask "aldente"
cask "alfred"
cask "amethyst"
cask "dropbox"
cask "easy-move-plus-resize"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-sans"
cask "google-chrome"
cask "jabra-direct"
cask "libreoffice"
cask "nomachine-enterprise-client"
cask "opera-developer"
cask "scroll-reverser"
cask "shifty"
cask "signal"
cask "skype"
cask "slack"
cask "smooze"
cask "sonos-s1-controller"
cask "tunnelblick"
cask "ukelele"
cask "visual-studio-code"
cask "whichspace"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Ka-Block!", id: 1335413823
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
