---
require:
  - standard
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/ruby-2.3.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'

Layout/ClassStructure:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/NumberConversion:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConstantVisibility:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/IpAddresses:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/StringHashKeys:
  Enabled: true
