# ~/.config/starship.toml

add_newline = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = true
truncation_length = 4
truncation_symbol = "…/"

[line_break]
disabled = false

[memory_usage]
disabled = false

[status]
disabled = false
map_symbol = true
pipestatus = true

[sudo]
disabled = false
