# ~/.config/starship.toml

add_newline = false

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 4
truncation_symbol = "…/"

[line_break]
disabled = false

[memory_usage]
disabled = false

[status]
disabled = false
pipestatus = true
