#!/bin/bash

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                               \
  mouse_follows_focus          off            \
  focus_follows_mouse          off            \
  window_origin_display        default        \
  window_placement             second_child   \
  window_zoom_persist          on             \
  insert_feedback_color        0xffd75f5f     \
  split_ratio                  0.50           \
  split_type                   auto           \
  auto_balance                 off            \
  top_padding                  0              \
  bottom_padding               0              \
  left_padding                 0              \
  right_padding                0              \
  window_gap                   0              \
  layout                       bsp            \
  mouse_modifier               alt            \
  mouse_action1                move           \
  mouse_action2                resize         \
  mouse_drop_action            swap

# global settings only with disabled System Integrity Protection
# yabai -m config                                 \
#   window_shadow                on             \
#   window_animation_duration    0.0            \
#   window_animation_frame_rate  120            \
#   window_opacity_duration      0.0            \
#   active_window_opacity        1.0            \
#   normal_window_opacity        0.90           \
#   window_opacity               off

FLOATING_APPS=(
  Activity Monitor
  AlDente
  App Store
  Bitwarden
  Calculator
  Calendar
  Contacts
  Dictionary
  Discord
  FaceTime
  FindMy
  Finder
  Home
  Lunar
  Mail
  Music
  Notes
  OrbStack
  Overcast
  PhotoBooth
  Raivo
  Raycast
  Reminders
  Stocks
  System Information
  System Preferences
  Tailscale
  Voice Memos
  Weather
  Zoom
  zoom.us
)
FLOATING_APPS_REGEX="$(IFS=\| ; echo "${FLOATING_APPS[*]}")"

yabai -m rule --add app="${FLOATING_APPS_REGEX}" manage=off

yabai -m signal --add event=window_created app!="${FLOATING_APPS_REGEX}" \
  action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

echo "$(date '+%F %T%z') yabai configuration loaded"
